[package]
name = "unpacker"
version.workspace = true
edition = "2024"

[lib]
name = "unpacker"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
log.workspace = true
image.workspace = true
lz4_flex.workspace = true
memmap2.workspace = true
num_enum.workspace = true
mr0k.workspace = true
texture2ddecoder = { path = "../../lib/texture2ddecoder" }
texture_decoder = { path = "../../lib/texture_decoder" }
