[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "hsr-frontend"
path = "src/main.rs"

[dependencies]
gpui.workspace = true
gpui_platform.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
hsr-ipc.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
log.workspace = true
smol.workspace = true
prost.workspace = true
protobuf3.workspace = true
protox.workspace = true
base64.workspace = true
rfd.workspace = true
full_moon.workspace = true
stylua.workspace = true
prism128.workspace = true
rand_core.workspace = true
unpacker.workspace = true
design.workspace = true
gacha.workspace = true
image.workspace = true
rayon.workspace = true
arboard.workspace = true
morax.workspace = true
mimalloc.workspace = true
ureq.workspace = true

[build-dependencies]
winres = "0.1"
image = "0.25"
