[package]
name = "dumper"
version = "0.1.0"
edition = "2024"

[lib]
name = "version"
crate-type = ["rlib", "cdylib"]

[dependencies]
windows.workspace = true
il2cpp.workspace = true
utils.workspace = true
reflection.workspace = true
base64.workspace = true
convert_case.workspace = true
serde.workspace = true
serde_json.workspace = true
ilhook.workspace = true
microseh.workspace = true
iced-x86.workspace = true
indexmap.workspace = true
indicatif.workspace = true
dahlah-derive.workspace = true
anyhow.workspace = true
sniffer.workspace = true
cheat.workspace = true
hsr-ipc.workspace = true
log.workspace = true
ureq.workspace = true
byteorder.workspace = true
prost.workspace = true
cc.workspace = true
