mod fields;
pub use crate::lua::opcodes::fields::*;

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Op {
    Nop,
    Break,
    LoadNil,
    LoadB,
    LoadN,
    LoadK,
    Move,
    GetGlobal,
    SetGlobal,
    GetUpval,
    SetUpval,
    CloseUpvals,
    GetImport,
    GetTable,
    SetTable,
    GetTableKS,
    SetTableKS,
    GetTableN,
    SetTableN,
    NewClosure,
    NameCall,
    Call,
    Return,
    Jump,
    JumpBack,
    JumpIf,
    JumpIfNot,
    JumpIfEq,
    JumpIfLe,
    JumpIfLt,
    JumpIfNotEq,
    JumpIfNotLe,
    JumpIfNotLt,
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    Pow,
    AddK,
    SubK,
    MulK,
    DivK,
    ModK,
    PowK,
    Band,
    Bor,
    BandK,
    BorK,
    And,
    Or,
    AndK,
    OrK,
    Concat,
    Not,
    Minus,
    Length,
    NewTable,
    DupTable,
    SetList,
    ForNPrep,
    ForNLoop,
    ForGLoop,
    ForGPrepInext,
    DepForGLoopInext,
    ForGPrepNext,
    NativeCall,
    GetVarargs,
    DupClosure,
    PrepVarargs,
    LoadKX,
    JumpX,
    FastCall,
    Coverage,
    Capture,
    DepJumpIfEqK,
    DepJumpIfNotEqK,
    FastCall1,
    FastCall2,
    FastCall2K,
    ForGPrep,
    JumpXEqKNil,
    JumpXEqKB,
    JumpXEqKN,
    JumpXEqKS,
    Idiv,
    IdivK,
    Unknown(u8),
}

const STOCK: [Op; 81] = [
    Op::Nop,
    Op::Break,
    Op::LoadNil,
    Op::LoadB,
    Op::LoadN,
    Op::LoadK,
    Op::Move,
    Op::GetGlobal,
    Op::SetGlobal,
    Op::GetUpval,
    Op::SetUpval,
    Op::CloseUpvals,
    Op::GetImport,
    Op::GetTable,
    Op::SetTable,
    Op::GetTableKS,
    Op::SetTableKS,
    Op::GetTableN,
    Op::SetTableN,
    Op::NewClosure,
    Op::NameCall,
    Op::Call,
    Op::Return,
    Op::Jump,
    Op::JumpBack,
    Op::JumpIf,
    Op::JumpIfNot,
    Op::JumpIfEq,
    Op::JumpIfLe,
    Op::JumpIfLt,
    Op::JumpIfNotEq,
    Op::JumpIfNotLe,
    Op::JumpIfNotLt,
    Op::Add,
    Op::Sub,
    Op::Mul,
    Op::Div,
    Op::Mod,
    Op::Pow,
    Op::AddK,
    Op::SubK,
    Op::MulK,
    Op::DivK,
    Op::ModK,
    Op::PowK,
    Op::And,
    Op::Or,
    Op::AndK,
    Op::OrK,
    Op::Concat,
    Op::Not,
    Op::Minus,
    Op::Length,
    Op::NewTable,
    Op::DupTable,
    Op::SetList,
    Op::ForNPrep,
    Op::ForNLoop,
    Op::ForGLoop,
    Op::ForGPrepInext,
    Op::DepForGLoopInext,
    Op::ForGPrepNext,
    Op::NativeCall,
    Op::GetVarargs,
    Op::DupClosure,
    Op::PrepVarargs,
    Op::LoadKX,
    Op::JumpX,
    Op::FastCall,
    Op::Coverage,
    Op::Capture,
    Op::DepJumpIfEqK,
    Op::DepJumpIfNotEqK,
    Op::FastCall1,
    Op::FastCall2,
    Op::FastCall2K,
    Op::ForGPrep,
    Op::JumpXEqKNil,
    Op::JumpXEqKB,
    Op::JumpXEqKN,
    Op::JumpXEqKS,
];

impl Op {
    pub fn decode(byte: u8) -> Op {
        match byte {
            0..=44 => STOCK[byte as usize],
            45 => Op::Band,
            46 => Op::Bor,
            47 => Op::BandK,
            48 => Op::BorK,
            49..=84 => STOCK[(byte - 4) as usize],
            85 => Op::Idiv,
            86 => Op::IdivK,
            other => Op::Unknown(other),
        }
    }

    pub fn length(self) -> usize {
        use Op::*;
        match self {
            GetGlobal | SetGlobal | GetImport | GetTableKS | SetTableKS | NameCall | NewTable
            | SetList | ForGLoop | LoadKX | FastCall2 | FastCall2K | JumpIfEq | JumpIfLe
            | JumpIfLt | JumpIfNotEq | JumpIfNotLe | JumpIfNotLt | JumpXEqKNil | JumpXEqKB
            | JumpXEqKN | JumpXEqKS | DepJumpIfEqK | DepJumpIfNotEqK => 2,
            _ => 1,
        }
    }

    pub fn name(self) -> &'static str {
        use Op::*;
        match self {
            Nop => "NOP",
            Break => "BREAK",
            LoadNil => "LOADNIL",
            LoadB => "LOADB",
            LoadN => "LOADN",
            LoadK => "LOADK",
            Move => "MOVE",
            GetGlobal => "GETGLOBAL",
            SetGlobal => "SETGLOBAL",
            GetUpval => "GETUPVAL",
            SetUpval => "SETUPVAL",
            CloseUpvals => "CLOSEUPVALS",
            GetImport => "GETIMPORT",
            GetTable => "GETTABLE",
            SetTable => "SETTABLE",
            GetTableKS => "GETTABLEKS",
            SetTableKS => "SETTABLEKS",
            GetTableN => "GETTABLEN",
            SetTableN => "SETTABLEN",
            NewClosure => "NEWCLOSURE",
            NameCall => "NAMECALL",
            Call => "CALL",
            Return => "RETURN",
            Jump => "JUMP",
            JumpBack => "JUMPBACK",
            JumpIf => "JUMPIF",
            JumpIfNot => "JUMPIFNOT",
            JumpIfEq => "JUMPIFEQ",
            JumpIfLe => "JUMPIFLE",
            JumpIfLt => "JUMPIFLT",
            JumpIfNotEq => "JUMPIFNOTEQ",
            JumpIfNotLe => "JUMPIFNOTLE",
            JumpIfNotLt => "JUMPIFNOTLT",
            Add => "ADD",
            Sub => "SUB",
            Mul => "MUL",
            Div => "DIV",
            Mod => "MOD",
            Pow => "POW",
            AddK => "ADDK",
            SubK => "SUBK",
            MulK => "MULK",
            DivK => "DIVK",
            ModK => "MODK",
            PowK => "POWK",
            Band => "BAND",
            Bor => "BOR",
            BandK => "BANDK",
            BorK => "BORK",
            And => "AND",
            Or => "OR",
            AndK => "ANDK",
            OrK => "ORK",
            Concat => "CONCAT",
            Not => "NOT",
            Minus => "MINUS",
            Length => "LENGTH",
            NewTable => "NEWTABLE",
            DupTable => "DUPTABLE",
            SetList => "SETLIST",
            ForNPrep => "FORNPREP",
            ForNLoop => "FORNLOOP",
            ForGLoop => "FORGLOOP",
            ForGPrepInext => "FORGPREP_INEXT",
            DepForGLoopInext => "FORGLOOP_INEXT",
            ForGPrepNext => "FORGPREP_NEXT",
            NativeCall => "NATIVECALL",
            GetVarargs => "GETVARARGS",
            DupClosure => "DUPCLOSURE",
            PrepVarargs => "PREPVARARGS",
            LoadKX => "LOADKX",
            JumpX => "JUMPX",
            FastCall => "FASTCALL",
            Coverage => "COVERAGE",
            Capture => "CAPTURE",
            DepJumpIfEqK => "JUMPIFEQK",
            DepJumpIfNotEqK => "JUMPIFNOTEQK",
            FastCall1 => "FASTCALL1",
            FastCall2 => "FASTCALL2",
            FastCall2K => "FASTCALL2K",
            ForGPrep => "FORGPREP",
            JumpXEqKNil => "JUMPXEQKNIL",
            JumpXEqKB => "JUMPXEQKB",
            JumpXEqKN => "JUMPXEQKN",
            JumpXEqKS => "JUMPXEQKS",
            Idiv => "IDIV",
            IdivK => "IDIVK",
            Unknown(_) => "UNKNOWN",
        }
    }
}
