[package]
name = "design"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
base64.workspace = true
indexmap.workspace = true
rayon.workspace = true
log.workspace = true

varint-rs = { version = "2.2.0", features = ["signed"] }
byteorder = "1.5.0"
xxhash-rust = { version = "0.8.15", features = ["const_xxh64"] }
hex = "0.4.3"
md-5 = "0.10.6"
dashmap = { version = "6.1.0", features = ["rayon"] }
walkdir = "2.5.0"
tracing = "0.1"
