[package]
name = "il2cpp"
version = "0.1.0"
edition = "2024"

[dependencies]
paste.workspace = true
utils.workspace = true
microseh.workspace = true
bitflags.workspace = true
anyhow.workspace = true
dahlah-derive.workspace = true
indexmap.workspace = true
windows.workspace = true
serde_json.workspace = true
log.workspace = true
inventory.workspace = true
