[package]
name = "reflection"
version = "0.1.0"
edition = "2024"

[dependencies]
il2cpp.workspace = true
serde_json.workspace = true
microseh.workspace = true
dahlah-derive.workspace = true
anyhow.workspace = true
bitflags.workspace = true
indexmap.workspace = true
log.workspace = true
inventory.workspace = true
